name: Upload Questions

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths:
      - '**.questions.yaml'
      - '**.lesson.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.questions.yaml'
      - '**.lesson.yaml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.3.1

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          pip install PyYaml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: execute script
        run: python .github/upload_questions.py